
development:
  adapter: mysql2
  database: swTucson_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: swTucson_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: swTucson_production
  username: root
  password: 
  encoding: utf8
